apiVersion: argoproj.io/v1
kind: Application
metadata:
  name: argocd-app-frontend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/WaddenSeaSolutions/DOLS-Compulsory-2
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
      
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app.kubernetes.io/name: applications.argoproj.io
      app.kubernetes.io/part-of: argocd
    name: applications.argoproj.io
  spec:
    group: argoproj.io
    names:
      kind: Application
      listKind: ApplicationList
      plural: applications
      shortNames:
        - app
        - apps
      singular: application
