version: '3.8'

services:
  dols-app:
    build:
      context: .
      dockerfile: DOLS-Compulsory-2.Server/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
    volumes:
      - ./app-data:/app/data
    restart: unless-stopped

networks:
  default:
    driver: bridge