version: '3.8'

services:
  dols-app:
    build:
      context: .
      dockerfile: DOLS-Compulsory-2.Server/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    # ports:
    #   # - "8080:8080"
    #   # - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - FLAGSMITH_API_KEY
    volumes:
      - ./app-data:/app/data
    restart: unless-stopped
    deploy:
     replicas: 2 # Starts 2 instances of dols-app
    
  dols-frontend:
    build:
      context: . 
      dockerfile: dols-compulsory-2.client/Dockerfile
    ports:
      - "32116:32116"
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: DB
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3300:3306"  # Binder port 3300 på værten til 3306 inde i containeren
  
  userdb:
    image: mariadb:latest
    container_name: user_mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3301:3306"

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    depends_on:
      - dols-app
      - dols-frontend
    volumes:
      - C:/Users/jonas/Desktop/RiderProjects/DOLS-Compulsory-2/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

networks:
  default:
    driver: bridge