apiVersion: apps/v1
kind: Deployment
metadata:
  name: dols-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dols-frontend
  template:
    metadata:
      labels:
        app: dols-frontend
    spec:
      containers:
        - name: dols-frontend
          image: your-registry/dols-frontend:latest
          ports:
            - containerPort: 32116
