name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push backend image
      run: |
        docker build -t your-docker-repo/backend:${GITHUB_SHA} ./backend
        docker push your-docker-repo/backend:${GITHUB_SHA}

    - name: Build and push frontend image
      run: |
        docker build -t your-docker-repo/frontend:${GITHUB_SHA} ./frontend
        docker push your-docker-repo/frontend:${GITHUB_SHA}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up kubectl
      uses: actions/setup-kubectl@v2
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment-backend.yaml
        kubectl apply -f k8s/deployment-frontend.yaml

    - name: Wait for deployment to complete
      run: |
        kubectl rollout status deployment/backend-deployment
        kubectl rollout status deployment/frontend-deployment
