name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push backend image
      run: |
        docker build -t andreaseriksen/backend:${GITHUB_SHA} -f ./DOLS-Compulsory-2.Server/Dockerfile .
        docker tag andreaseriksen/backend:${GITHUB_SHA} andreaseriksen/backend:latest
        docker push andreaseriksen/backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t andreaseriksen/frontend:${GITHUB_SHA} -f ./dols-compulsory-2.client/Dockerfile .
        docker tag andreaseriksen/frontend:${GITHUB_SHA} andreaseriksen/frontend:latest
        docker push andreaseriksen/frontend:latest
